[33mcommit df5214fbfc7bbfcedf8399394a0e4010dc03cf59[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mnested-to-mutual[m[33m, [m[1;31morigin/nested-to-mutual[m[33m)[m
Author: Thomas Lamiaux <thomas.lamiaux@gmail.com>
Date:   Tue Mar 11 21:34:20 2025 +0100

    Add View Nested + Positivity + Partial (Nested to Mutual + Proof Pos)

[33mcommit d19cfb98b9dc51372d535c3da7c4612eee931820[m[33m ([m[1;31morigin/coq-8.20[m[33m, [m[1;32mcoq-8.20[m[33m)[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Feb 19 16:03:13 2025 +0100

    Merge pull request #1113 from MathisBD/tm-unquote-evars
    
    Improve evar handling in tmUnquote/tmUnquoteTyped

[33mcommit 1d9755adac8bf50d884c75236f7b860ffc0114a5[m[33m ([m[1;33mtag: [m[1;33mv1.3.4-8.20[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jan 27 13:09:07 2025 +0100

    Remove autogenerated file from VCS

[33mcommit 05ba4dd81729b7fd01d9817d614ec0e18b55e8c1[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Jan 27 11:23:13 2025 +0100

    dependabot 8.20

[33mcommit a8f8957859cf1621d5adf5debeef35f48b73acf8[m
Author: 4ever2 <3417013+4ever2@users.noreply.github.com>
Date:   Fri Nov 8 12:58:05 2024 +0100

    Fix substitution during eta expansion of partial application

[33mcommit 22b93edecb0029e48f73847d7b672af105c08c4a[m
Author: Jason Gross <jgross@mit.edu>
Date:   Wed Oct 16 12:41:08 2024 -0700

    dependabot updates for coq-8.19 branch

[33mcommit 25f8016405d518d70fa90c830c4cb9c67cc6fe6f[m
Author: Tan Yee Jian <tanyeejian@gmail.com>
Date:   Mon Sep 16 11:14:49 2024 +0200

    Point 'index' in CoqDocJS header to index.html (#1094)

[33mcommit ea3ed3c4b0d05508ce744f17a56c880c5f47c816[m
Merge: 0b90e692 9df908f6
Author: MathisBD <75327344+MathisBD@users.noreply.github.com>
Date:   Mon Dec 30 20:43:18 2024 +0100

    Merge pull request #1131 from MathisBD/update-inductive-doc-8.20
    
    Update documentation in common/Environment.ml for inductive and constant declarations

[33mcommit 9df908f69f24127403360959c8b2ecf0c45dc745[m
Author: MathisBD <mathis.bouverot@ens.psl.eu>
Date:   Mon Dec 30 16:38:38 2024 +0100

    update documentation

[33mcommit 8d8a2fd637622f9de7662961907416197feca4cd[m
Author: MathisBD <mathis.bouverot@ens.psl.eu>
Date:   Thu Dec 12 14:34:40 2024 +0100

    add documentation in common/Environment.v

[33mcommit 0b90e6924f9a781ff5beb9a786a019d76aa0b77a[m
Merge: 5672294a 1fff46d0
Author: MathisBD <75327344+MathisBD@users.noreply.github.com>
Date:   Wed Dec 4 17:46:37 2024 +0100

    Merge pull request #1126 from MathisBD/fix-bugged-option
    
    Remove bugged option MetaCoq Template Monad Debug.

[33mcommit 1fff46d0c2edaab6ec237a1b3d0476fca7416215[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Mon Nov 25 18:21:32 2024 +0100

    Remove bugged option MetaCoq Template Monad Debug.
    
    It causes https://github.com/coq/vscoq/issues/892 because `optwrite`
    is not supposed to be able to add persistent objects (libobject) to
    Coq's state but `set_option_value` does add one.
    
    It's also bugged as
    `set_option_value ~stage:Interp (fun _ v -> v) key i`
    sets the option to its current value not a new value.
    In other words `Set MetaCoq Template Monad Debug.` has no effect but
    its existence causes bugs.
    
    Since nobody complained about it not working it's not worth fixing it
    instead of deleting it (also I'm not sure it can be fixed with the
    currently available APIs).

[33mcommit 5672294a99a0275ce8d4e10ded692c3cc92a163e[m
Author: MathisBD <75327344+MathisBD@users.noreply.github.com>
Date:   Mon Nov 25 10:13:40 2024 +0100

    initial commit (#1122)
    
    Co-authored-by: Yannick Forster <yannick.forster@inria.fr>
    Co-authored-by: Théo Winterhalter <theo.winterhalter@inria.fr>

[33mcommit 6e75b709a5b8dd984cd63279dc3c48aa884757df[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Fri Nov 22 15:03:18 2024 +0100

    Mention 8.20 in DOC.md and INSTALL.md (#1121)

[33mcommit f251f2ac04e91050f67972bef4166dcef88b3f24[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 30 15:50:15 2024 +0100

    Fix quoting and unquoting of primitive strings (#1109) for 8.29 (#1110)
    
    * initial fix
    
    * update test-suite
    
    Co-authored-by: MathisBD <75327344+MathisBD@users.noreply.github.com>

[33mcommit b59ea922a0cd2985f62fb7cac00334054df166ef[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Sep 3 13:46:13 2024 +0200

    Update make-opam-files script

[33mcommit f7f6ede66abbf998a85b165ac580df56bb26a309[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Mon Jul 1 16:30:28 2024 +0200

    Remove unneeded problematic universe constraints

[33mcommit c8e165840a0b90e78f1d3f9adb2fe11974ef95ad[m[33m ([m[1;33mtag: [m[1;33mv1.3.2-8.20[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Aug 23 17:53:10 2024 +0200

    Fix erasure_live_test

[33mcommit 4676c4736864e1ca7ccd1da9766473a72518443a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Aug 23 17:14:38 2024 +0200

    Fixes after merge

[33mcommit b5bd6e5e81ca233dab6b863aada623a4628ec204[m
Merge: 13a68523 b1b6be23
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Aug 23 15:48:38 2024 +0200

    Merge branch 'coq-8.19' into coq-8.20

[33mcommit b1b6be23e00fefba6a03c153a458e72acb463daa[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jul 22 16:24:42 2024 +0200

    make-opam-files now computes the appropriate ci-skip line

[33mcommit 462f3abaab68e5ca3fd861fcee29c660a2570b5b[m[33m ([m[1;33mtag: [m[1;33mv1.3.2-8.19[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jul 22 14:46:51 2024 +0200

    Proof that reordering of constructors is correct (#1095)
    
    * WIP on reordering constructors
    
    * New/old tag reasoning
    
    * WIP correctness of constructor reordering. main lemma proven
    
    * Reordering preserves well-formedness
    
    * Reorderin
    
    * Admit free proofs of preservation for wf and substitution
    
    * WIP adapting to an additional mapping argument for transforms and stronger wellformedness property on extracted terms
    
    * Full composed pipeline with mapping of constructors
    
    * Fixes due to removal of useless -fast flag and change for reordering of constructors, now verified
    
    * Remove option to reorder constructors, now safely done always
    
    * Fix metacoq_tour
    
    * Fix a remaining todo
    
    * Remove generated files

[33mcommit 13a68523f688faa040263929e6cd11dcb7c11970[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jul 9 14:50:21 2024 +0200

    Update opam file dependencies for 8.20 version

[33mcommit 052e6fc258bc2b4f5153550c4ab8396f59315997[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jul 9 14:48:16 2024 +0200

    Use 8.20 in CI

[33mcommit fc72216a331b4e8aa3c19e17bc1f4df62bda3175[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jul 9 14:46:16 2024 +0200

    No longer needed stdlib-shims dependency

[33mcommit 52fda991e207560dcfe916fb98c7a71cd4f2d65b[m
Merge: b4d67e4d 9cdb37bb
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jul 9 13:57:42 2024 +0200

    Merge pull request #1092 from MetaCoq/clean-_project_files
    
    Remove generated files from archive and ignore them now

[33mcommit 9cdb37bb79af1c37e2fba8b8cdd6f806108e4b85[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jul 8 10:47:12 2024 +0200

    Fix translations due to new tString constructor

[33mcommit ec45ca30068a4b8bb4b2519b3839c96a729e0f20[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jul 8 10:20:50 2024 +0200

    Remove generated files from archive and ignore them now

[33mcommit b4d67e4dbd075fe3f0fdd5566cc56ab345afcfa6[m
Merge: b9739c12 78561fcd
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Fri Jun 14 23:06:11 2024 +0200

    Merge pull request #1088 from rlepigre/br/prim-string
    
    Adapt to coq/coq#18973.

[33mcommit b9739c12ffc8a379cade629d7ab2fa44f966c38c[m
Merge: 7f820b6f be63a888
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jun 12 14:35:38 2024 +0200

    Merge pull request #1081 from mrhaandi/faster-PCUICSR
    
    faster PCUICSR

[33mcommit 7f820b6f31457f12696c84cf6a56579c23a02f93[m
Merge: 35dbb48f 1dd3fd19
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jun 12 14:34:12 2024 +0200

    Merge pull request #1079 from silene/remove-vm
    
    Remove useless calls to Eval vm_compute.

[33mcommit 78561fcdaf77413f9f8fe9e77502938cf72f32db[m
Author: Rodolphe Lepigre <lepigre@mpi-sws.org>
Date:   Tue Jun 4 16:35:41 2024 +0200

    Adapt to coq/coq#18973.

[33mcommit 13dc7ce5b1526ee783722ff4985249951704116d[m
Merge: f55eb7c2 a4cd12c5
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jun 7 11:38:03 2024 +0200

    Merge pull request #1089 from MetaCoq/force-lazy-evaluation
    
    Add the `force (lazy t)` evaluation rule to LambdaBox

[33mcommit a4cd12c5726818ed1f155ab79904ef0de5f9a815[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Jun 6 18:38:53 2024 +0200

    Add the force (lazy t) evaluation rule to lambda-box

[33mcommit 35dbb48f204a918be13519e3ee9a2bf105a073fb[m
Merge: d6e0f45d 9a28be1e
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue May 28 17:41:48 2024 +0200

    Merge pull request #1083 from herbelin/main+adapt-coq-pr18795-more-uniform-declare.ml
    
    Adapt to Coq PR #18795 (more uniform API for declare.ml)

[33mcommit d6e0f45ded30d0c2781c917331bebf3a4234ed6e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu May 23 12:09:45 2024 +0200

    Make scripts more robust when using simp and solving the goal trivially.

[33mcommit d1f8f553fc0df7fc680e91cb8bc389cb3a48851b[m
Merge: e27b5492 526bc84a
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed May 22 14:17:41 2024 +0200

    Merge pull request #1085 from MetaCoq/fixes-for-funelim
    
    Fixes for funelim

[33mcommit 526bc84adb9e892173ad8767bbba38aca4679c8a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed May 22 11:42:37 2024 +0200

    Fixes for compatibility with Coq master

[33mcommit 8bb76fb32cd766728e84d57a389e87dcfdc76ad7[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed May 22 09:46:31 2024 +0200

    Backward compatible fixes for update of equations funelim tactic bugfix.

[33mcommit e60558aed638e9431593a97da44fb642a952a696[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue May 21 13:43:50 2024 +0200

    Backward compat fix of funelim proof

[33mcommit 555d5e6ffc733ff0e7413289163d88c0e1a6cddb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue May 21 13:40:02 2024 +0200

    Fix deprecations

[33mcommit 1eaac6803d5e96140199b359a0e9d0f0f757f9e0[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Mar 19 10:24:20 2024 +0100

    Update make_opam_files to upload the archive to the releases folder on github to avoid issues with github rebuilding the tarballs

[33mcommit 85296fae686c399c65a87caf8332519ff5b6734e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:35:34 2024 +0100

    Fix after merge

[33mcommit 49241c0adf003bdcc82f660af4c1f836b55ea6a2[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:33:50 2024 +0100

    Fix script due to misclassification of implicit arg as potential typeclass instance

[33mcommit 0c34397b617051f3efc8cf243ecb0c707a10b803[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 15 17:24:44 2024 +0100

    Fix issue #1042 MetaCoq Run does not support evars.

[33mcommit b1e6dcd0ddaef2c0bb45652bd6df4ec22e6cb1dc[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:11:56 2024 +0100

    Fix deprecation and unnecessary module

[33mcommit 979702a201c4b83259b53c083b9730846d0c0451[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 8 09:51:00 2024 +0100

    Fix inlining and reorder constructors which were not translating let bindings... oops!

[33mcommit 975558ffae6365af68946a26db8550c676151928[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Mar 7 08:38:28 2024 +0100

    Fix typo

[33mcommit cae22c6ee57b37d8bc3d2d857dd47fb5ce582651[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Mar 6 10:11:08 2024 +0100

    Split unsafe passes, update EWcbvEvalNamed to be more parametric on flags

[33mcommit 0bd01a2eca72e770cb2be531df169fa29c065e0e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Mar 2 00:01:49 2024 +0100

    WIP improving ewcbvevalnamed, needs to consider cofixes

[33mcommit 66556ddbf43729869f9705006af47a2958584f2f[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 29 09:32:40 2024 +0100

    Implement a general Show typeclass in MetaCoq.Utils (#1063)
    
    * Implement a general Show typeclass in MetaCoq.Utils
    
    * Fix dependencies of new template-coq plugin

[33mcommit e8dcbde62a82a1e88595d19a0838202e34f30035[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Feb 23 14:20:37 2024 +0100

    Unsafe inlining and beta-reduction transfomations

[33mcommit 2fc4f829b330f2547208afebf4a095a0c1f5e871[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 22 18:12:03 2024 +0100

    Implement unboxing structurally (cstrs as blocks version)

[33mcommit 4655e64c7315757cd48c728b424242542cd52f7f[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Feb 12 07:26:09 2024 +0100

    WIP unboxing transform

[33mcommit 5cfde701aaedb18b264f8f9e4cf50f7fdf3cb4bd[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 21 17:58:38 2024 +0100

    Make reordering function transparent so it can compute in Coq

[33mcommit 61aeb69c829398a192b61ace7592cb4099a4c6ee[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 21 11:32:24 2024 +0100

    Implement reordering of constructors (for Extract Inductive)

[33mcommit e233e8d9748bdd02a4f6ac620084f56cb80483d1[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Mar 19 10:45:33 2024 +0100

    Implement tLazy and tForce in EAst (#1058)
    
    * Add tLazy and tForce constructors
    
    With no evaluation semantics yet. Use them in ECoInductiveToInductive to allow efficient (unverified) implementation of cofixpoints in target languages.
    
    * Install archive file for static linking

[33mcommit 9acfd0cf089b3e6a1d803df2f7059e3d7c3da6b2[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Mon Feb 19 12:12:30 2024 +0100

    clean up in ErasureCorrectness

[33mcommit d99f256cf4407d21e047374144315d11824d1830[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Feb 17 10:52:24 2024 +0100

    Avoid Ee := EWcbvEval module aliases which result in ugly extraction issues (#1057)

[33mcommit d9b19cccfd5063748a1734087f32ff1383799026[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 14 07:47:52 2024 +0100

    Resurrect the cofix transform, adding a new axiom for the admitted pr… (#1056)
    
    * Resurrect the cofix transform, adding a new axiom for the admitted proofs.
    Generalize `MetaCoq Erase` to take options allowing to optionally run this pass
    
    * Minor fixes
    
    * Fix metacoq_tour
    
    * Fix quoting of cofix to make translation correct

[33mcommit 099ef7aba4cf7a55e1fd246840b01c207b5c8afb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 15:43:42 2024 +0100

    Erase function lemma (#1053)
    
    * Fix typed erasure calls to _not_ trim inductive masks
    
    * Comment WIP app_construct proof
    
    * Comment WIP erase_function proof
    
    * Prove that functions are preserved by compilation
    
    * Show that inhabitants of product types evaluate to functions through the erasure pipeline

[33mcommit 7039be26ba8235b44140dcb847eed3433f5a8491[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 09:21:59 2024 +0100

    Fix test-suite file

[33mcommit 172ce0fdda546d9aafcfbaa1a330cb506873aa63[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 07:24:18 2024 +0100

    Fix typed erasure calls to _not_ trim inductive masks

[33mcommit f980cc9fcdd58c7ed1475ce4b2a06cfc58ad4b95[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Feb 13 07:33:26 2024 +0100

    generalize verified_erasure_pipeline_lookup_env_in

[33mcommit ac8cc36b97a03a09f5481e4b8591bdce33f34b17[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 1 12:07:19 2024 +0100

    Fill proofs

[33mcommit 8921ad9730140b056fd8d0a4f87de2d9eb297cac[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Jan 30 09:32:50 2024 +0100

    erasure_pipeline_extends_app with todo irrel

[33mcommit 9a28be1ef8a05c1a3fa48ad952154bd306f525b7[m
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Thu Apr 18 23:07:33 2024 +0200

    Adapt to PR #18795

[33mcommit be63a88847dc59aad8f1aa9cb2c509468c63dfd6[m
Author: Andrej Dudenhefner <mrhaandi@gmail.com>
Date:   Wed May 8 14:10:31 2024 +0200

    replace slow firstorder by appropriate constructor

[33mcommit e27b5492b3e23cda32464dd20766966a63de77cc[m
Merge: d8c5fe08 755a9823
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 23 19:17:24 2024 +0200

    Merge pull request #1080 from SkySkimmer/erelevance
    
    Adapt to coq/coq#18938 (EConstr.ERelevance)

[33mcommit d8c5fe084ebb47a67c9e14010bc3d6e97ca4fa35[m
Merge: 1e2bbd0d 29fc39c9
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Thu Apr 18 21:26:49 2024 +0200

    Merge pull request #1073 from SkySkimmer/non-prop-template
    
    Adapt to coq/coq#18867 (inductive_sort_family doesn't exist)

[33mcommit 755a9823eb25fed0839f31ca03aab1d37aeaed74[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Wed Apr 17 14:21:57 2024 +0200

    Adapt to coq/coq#18938 (EConstr.ERelevance)

[33mcommit 1e2bbd0daa1b3e32c034d18ef59d39a0dd2720be[m
Merge: eb4ea19d 10ed5fb9
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Sat Apr 13 16:40:09 2024 +0200

    Merge pull request #1078 from herbelin/main+adapt-coq-pr18921-program-return-clause
    
    Adapt to coq PR #18921 fixing bugs of the inference of the return clause for Program-style pattern-matching

[33mcommit 1dd3fd19ebb79c95f94e1388d1146269ec57676b[m
Author: Guillaume Melquiond <guillaume.melquiond@inria.fr>
Date:   Fri Apr 12 14:54:12 2024 +0200

    Remove useless calls to Eval vm_compute.
    
    These evaluations do not produce anything interesting, since the called
    function is just a wrapper around a function created by "Function
    the_loop. Admitted." and therefore opaque.

[33mcommit 10ed5fb9174bcd4c694f10f721b0b27505f820f2[m
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Wed Apr 10 21:22:39 2024 +0200

    Adapt to Coq PR #18921: change of return clause in Program Definition.

[33mcommit eb4ea19dc07d23eefe9c5849bb0f74d72c864fd5[m
Merge: 74918fca 2c0abea3
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 9 22:34:04 2024 +0200

    Merge pull request #1077 from ppedrot/hint-using-strict-globref
    
    Adapt w.r.t. coq/coq#18909.

[33mcommit 2c0abea33b641b48662c8cd8c2aacc057a66adc1[m
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 9 21:29:16 2024 +0200

    Adapt w.r.t. coq/coq#18909.

[33mcommit 74918fcaf881cc4eb7fe949909a31aaf6b3712fd[m
Merge: 6ec591bf 2d9b6f0b
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 9 17:30:04 2024 +0200

    Merge pull request #1076 from ppedrot/setoid-type-core-tc-opaque
    
    Adapt w.r.t. coq/coq#18910.

[33mcommit 2d9b6f0b58a6384c1d8ea6c73673ce4718365729[m
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 9 14:39:08 2024 +0200

    Adapt w.r.t. coq/coq#18910.

[33mcommit 6ec591bf2a541e265496df235d2a80dc859dc227[m
Merge: 9aa90869 70e4a905
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Apr 9 08:41:58 2024 +0200

    Merge pull request #1071 from SkySkimmer/redexpr-clean
    
    Adapt to coq/coq#18852 (interp_red_expr can be done without ltac)

[33mcommit 9aa908699e673499311a75d9d7954bf06a6001aa[m
Merge: 3eca445c 142cff12
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Sun Apr 7 12:28:46 2024 +0200

    Merge pull request #1074 from SkySkimmer/indirect
    
    Adapt to coq/coq#18422 (indirect accessor handled through vernactypes)

[33mcommit 142cff12693b4cabb16ca0068c249598a466d9a5[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Fri Apr 5 13:16:32 2024 +0200

    Adapt to coq/coq#18422 (indirect accessor handled through vernactypes)

[33mcommit 29fc39c9510b0d865dd4ad0092fc7d1324a4c971[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Apr 4 15:42:01 2024 +0200

    Adapt to coq/coq#18867 (inductive_sort_family doesn't exist)

[33mcommit 70e4a9053514efc1f1e539d80234910c35e8abdf[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Mar 28 16:33:47 2024 +0100

    Adapt to coq/coq#18852 (interp_red_expr can be done without ltac)

[33mcommit f55eb7c21ddfefde4cb08116232428e38ed2ee33[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Mar 19 10:24:20 2024 +0100

    Update make_opam_files to upload the archive to the releases folder on github to avoid issues with github rebuilding the tarballs

[33mcommit 9af0b0fc7b8c3a2989aae8a11e6a6b24695128ef[m[33m ([m[1;33mtag: [m[1;33mv1.3.1-8.19[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:35:34 2024 +0100

    Fix after merge

[33mcommit 5c8e1b07627cd88713eae612c53d85ff9b70652e[m
Merge: 4d71de94 96b80c94
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:34:21 2024 +0100

    Merge branch 'coq-8.18' into coq-8.19

[33mcommit 96b80c94f753e3bc92a8f932e01208017bb58594[m[33m ([m[1;33mtag: [m[1;33mv1.3.1-8.18[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:33:50 2024 +0100

    Fix script due to misclassification of implicit arg as potential typeclass instance

[33mcommit 4d71de942baf3ab66152e190d14da7e85005d380[m
Merge: 38324e47 65f3a822
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:15:17 2024 +0100

    Merge branch 'coq-8.18' into coq-8.19

[33mcommit 65f3a8223977dbc85d3978beac51fb03b26004bf[m
Merge: 05cffdfa 8a42c5bf
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:13:20 2024 +0100

    Merge branch 'coq-8.17' into coq-8.18

[33mcommit 05cffdfa5ae5c16c914b4720852cd2b81db08b60[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Mar 18 10:11:56 2024 +0100

    Fix deprecation and unnecessary module

[33mcommit 8a42c5bf6ab163a3032555e3a4a6471ee49e69fc[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 15 17:24:44 2024 +0100

    Fix issue #1042 MetaCoq Run does not support evars.

[33mcommit 3eca445c419b0e18c25858079ce48816537b927b[m
Merge: be825a7f 2814d2a9
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Thu Mar 14 17:04:54 2024 +0100

    Merge pull request #1035 from proux01/coq_18224
    
    Adapt to https://github.com/coq/coq/pull/18224

[33mcommit dfea0a52f537495ff319050efd07995364e058f7[m
Merge: 60374183 690e4437
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 8 15:07:11 2024 +0100

    Merge pull request #1066 from MetaCoq/fix-letin-inline-reorder
    
    Fix inlining and reorder constructors which were not translating let …

[33mcommit 897faa14c106e005a911c936edce0bc51cd548b5[m
Merge: 0b5845dd 690e4437
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 8 10:01:53 2024 +0100

    Merge branch 'fix-letin-inline-reorder' into coq-8.18

[33mcommit 690e443776a0ad1acaf39de5e065056d7711dfc7[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Mar 8 09:51:00 2024 +0100

    Fix inlining and reorder constructors which were not translating let bindings... oops!

[33mcommit 603741834df00f3dff90c308218eeeb044c241f8[m[33m ([m[1;33mtag: [m[1;33mv1.3-8.17[m[33m)[m
Merge: 9068e5b3 ec34006a
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Mar 7 09:47:05 2024 +0100

    Merge pull request #1065 from MetaCoq/fix-typo
    
    Fix typo

[33mcommit ec34006a3cc785d16e2178bb91f48f27ccba1a56[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Mar 7 08:38:28 2024 +0100

    Fix typo

[33mcommit 9068e5b3de032778e968204e9007c23b93de6fd5[m
Merge: 2cbbd670 e8e5ede7
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Mar 6 12:55:47 2024 +0100

    Merge pull request #1064 from MetaCoq/unsafe-and-ewcbvevalnamed
    
    Unsafe and ewcbvevalnamed

[33mcommit e8e5ede7ac77b7ae5966d65b6d692cc0cfd6da9a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Mar 6 10:11:08 2024 +0100

    Split unsafe passes, update EWcbvEvalNamed to be more parametric on flags

[33mcommit c8946aaf87ac540bb4493396e50ff78d52b7dd66[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Mar 2 00:01:49 2024 +0100

    WIP improving ewcbvevalnamed, needs to consider cofixes

[33mcommit 2cbbd67089305f50ea15f9f8f4bfc9d8ed66ab0a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 29 09:32:40 2024 +0100

    Implement a general Show typeclass in MetaCoq.Utils (#1063)
    
    * Implement a general Show typeclass in MetaCoq.Utils
    
    * Fix dependencies of new template-coq plugin

[33mcommit 260ce0d0255e2f9ebfd743b2173cd65ed5339211[m
Merge: f9c62c5e 9ee34f6b
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 28 10:54:21 2024 +0100

    Merge pull request #1061 from MetaCoq/unsafe-inline-beta
    
    Unsafe inline beta and unboxing transforms

[33mcommit 9ee34f6ba35173178cde5c5638513949d4680712[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Feb 23 14:20:37 2024 +0100

    Unsafe inlining and beta-reduction transfomations

[33mcommit 3be71de60284a8693365e287137845aa4256cf67[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 22 18:12:03 2024 +0100

    Implement unboxing structurally (cstrs as blocks version)

[33mcommit 5ed7a02771637982aa2e4affbd2cc865181c23bc[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Feb 12 07:26:09 2024 +0100

    WIP unboxing transform

[33mcommit f9c62c5e4253fe7039af731800b8e9c70f7fb98d[m
Merge: 9e3e264b e622b430
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 21 19:19:04 2024 +0100

    Merge pull request #1059 from MetaCoq/reorder-constructors
    
    Reorder constructors

[33mcommit e622b4308c8f03886a839ea0d994b8b2a598efe7[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 21 17:58:38 2024 +0100

    Make reordering function transparent so it can compute in Coq

[33mcommit be825a7f22e5747a123efb812008de5f44fd06a8[m
Merge: 25effb86 61e75d2d
Author: yannl35133 <40719961+yannl35133@users.noreply.github.com>
Date:   Wed Feb 21 14:44:47 2024 +0100

    Merge pull request #1060 from Yann-Leray/rewrite-rules-adapt
    
    Adapt to coq/coq#18038 (rewrite rules)

[33mcommit e896e06b7911c56020b4db3f9455c0f16169e735[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 21 11:32:24 2024 +0100

    Implement reordering of constructors (for Extract Inductive)

[33mcommit 25effb8651a75769fef8879f62a3ff582a9f49ff[m
Merge: 156fce56 dd294c9d
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Feb 20 19:38:22 2024 +0100

    Merge pull request #1029 from herbelin/main+adapt-coq-pr18397-declare_variable-api
    
    Adapt to Coq PR#18397: Declare.declare_variable now takes a "variable_declaration"

[33mcommit 9e3e264be33e248918b553150f1f2c4accb74392[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 20 13:50:43 2024 +0100

    Implement tLazy and tForce in EAst (#1058)
    
    * Add tLazy and tForce constructors
    
    With no evaluation semantics yet. Use them in ECoInductiveToInductive to allow efficient (unverified) implementation of cofixpoints in target languages.
    
    * Install archive file for static linking

[33mcommit 156fce561d56058fd29f4041df281455cc629273[m
Merge: e6368e35 a2fe2c6e
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Mon Feb 19 17:59:23 2024 +0100

    Merge pull request #1055 from proux01/coq_18590
    
    Adapt to https://github.com/coq/coq/pull/18590

[33mcommit f23a18c853a5809fb3c5e5c923ecd64b48145edc[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Mon Feb 19 12:12:30 2024 +0100

    clean up in ErasureCorrectness

[33mcommit 07c0a825a2a971704d5f09f9e828435aee96b83e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Feb 17 10:52:24 2024 +0100

    Avoid Ee := EWcbvEval module aliases which result in ugly extraction issues (#1057)

[33mcommit 6a26f385ce19b3204d93a81cd4e30994dbcd6ccf[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Feb 14 07:47:52 2024 +0100

    Resurrect the cofix transform, adding a new axiom for the admitted pr… (#1056)
    
    * Resurrect the cofix transform, adding a new axiom for the admitted proofs.
    Generalize `MetaCoq Erase` to take options allowing to optionally run this pass
    
    * Minor fixes
    
    * Fix metacoq_tour
    
    * Fix quoting of cofix to make translation correct

[33mcommit 99c6e851a8f7f2cafc6ca8cccdd5433b7df8b464[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 15:43:42 2024 +0100

    Erase function lemma (#1053)
    
    * Fix typed erasure calls to _not_ trim inductive masks
    
    * Comment WIP app_construct proof
    
    * Comment WIP erase_function proof
    
    * Prove that functions are preserved by compilation
    
    * Show that inhabitants of product types evaluate to functions through the erasure pipeline

[33mcommit ce312a84a7824351647fa0870808645364035770[m
Merge: bcf3ad5f 53b5abf2
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 10:30:48 2024 +0100

    Merge pull request #1052 from MetaCoq/fix-typed-erasure-calls
    
    Fix typed erasure calls

[33mcommit 53b5abf2acb385534a0ec6c1f301805bae315ead[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 09:21:59 2024 +0100

    Fix test-suite file

[33mcommit bcf3ad5f0f3de824e6ed800e0d166cf6f3bc7039[m
Merge: ff472bd0 3fbfc8e5
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Tue Feb 13 08:31:30 2024 +0100

    Merge pull request #1054 from MetaCoq/generalize-lookup_env_in
    
    generalize verified_erasure_pipeline_lookup_env_in

[33mcommit 3fbfc8e5935d0298c56d8b2aa34c175175ca29d7[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Feb 13 07:33:26 2024 +0100

    generalize verified_erasure_pipeline_lookup_env_in

[33mcommit f9d5fa69ef9a3a2524d1df2ec5843aaeeda412d9[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Feb 13 07:24:18 2024 +0100

    Fix typed erasure calls to _not_ trim inductive masks

[33mcommit 61e75d2dbac400252371881cd5d64a50b87756e4[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Mon Feb 5 16:25:47 2024 +0100

    Adapt to coq/coq#18038 (rewrite rules)

[33mcommit 2814d2a99b9d9da1d9ed6052440937fa16aaa60c[m
Author: Pierre Roux <pierre.roux@onera.fr>
Date:   Fri Nov 10 15:38:17 2023 +0100

    Adapt to https://github.com/coq/coq/pull/18224

[33mcommit a2fe2c6ebbabeb171575aebd63ba882efff0fe58[m
Author: Pierre Roux <pierre.roux@onera.fr>
Date:   Fri Feb 2 09:23:51 2024 +0100

    Adapt to https://github.com/coq/coq/pull/18590

[33mcommit ff472bd0bdd98347f9d1bfe49aee24f41392b5dc[m
Merge: 98b03601 78937906
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 1 14:02:48 2024 +0100

    Merge pull request #1050 from MetaCoq/erasure_pipeline_extends_app
    
    erasure_pipeline_extends_app with todo irrel

[33mcommit 78937906b8f15e10fe4f0b0b558cf9fddfbe1f14[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Feb 1 12:07:19 2024 +0100

    Fill proofs

[33mcommit 35b62250f812cbb9c46d34540c82d914fb3c55cf[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Jan 30 09:32:50 2024 +0100

    erasure_pipeline_extends_app with todo irrel

[33mcommit e6368e35d47efecf1d668e389fb1e790eac2db4a[m
Merge: 7de4179c 38324e47
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 19:03:08 2024 +0100

    Merge branch 'coq-8.19'

[33mcommit 38324e479547178777aaf0fe18a5147d7a80b145[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 19:00:27 2024 +0100

    Blacklist "Induction" in extraction due to clash with Coq module

[33mcommit 7de4179cd1466f52b1f7dfea9de98eb6f5c693ec[m
Merge: 4fbb3703 2feebad7
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 18:58:28 2024 +0100

    Merge branch 'coq-8.19'

[33mcommit 2feebad73e080325dd51c16d4a1f43fa41248fa7[m
Merge: f0e1d9d4 0b5845dd
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 18:57:24 2024 +0100

    Merge branch 'coq-8.18' into coq-8.19

[33mcommit 0b5845ddbd0f7338e22da8df32fc862017cbd6fe[m
Merge: a9acc324 98b03601
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 18:55:33 2024 +0100

    Merge branch 'coq-8.17' into coq-8.18

[33mcommit 98b0360169ba1dbc54f92ef50abd4c9dea7dfdc4[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 18:53:38 2024 +0100

    Use CArray.fold_left_map instead of rolling our own

[33mcommit 44c204b8e96ce7548a198fbf7ec0d6c594b0ce69[m
Merge: b674c5ea b3f2a125
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 18:43:18 2024 +0100

    Merge pull request #1040 from liyishuai/patch-1
    
    CI: multiple OCaml versions

[33mcommit 4fbb37035a7fb2b3516f25435b0cfa00db60e9f9[m
Merge: 5a4bb29f c7ba48b6
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 07:36:36 2024 +0100

    Merge pull request #1049 from MetaCoq/main-fixes-deprecations
    
    Main fixes deprecations

[33mcommit b674c5ea4d99611314c363bfa3b3b516b617f079[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 07:36:01 2024 +0100

    Comment certifying passes tests

[33mcommit ccb615ec6983554afe6b39138f63b724f76f6dcb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 07:13:37 2024 +0100

    Fix minor warnings

[33mcommit f0e1d9d49e79deb7dd6de42394e7169bb5646fae[m
Merge: 3f5c81df 7cb3ae77
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 07:07:59 2024 +0100

    Merge pull request #1048 from MetaCoq/8.19-warnings-deprecations
    
    8.19 warnings deprecations

[33mcommit a9acc32418ef1462ae286486f7d5de5bd7175e0d[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 07:06:15 2024 +0100

    Remove spurious coq.dev file

[33mcommit c7ba48b62ee183f1cd14aef3bc0b1394b5920efc[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Sat Jan 27 06:57:50 2024 +0100

    Fix warnings in quotation

[33mcommit f2b274447f0cbac2d782ea0b7b9fbbba95f96876[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 22:20:43 2024 +0100

    Fixes after merge (wrong opam deps)

[33mcommit bde7d3d488f76fcac84a0ee22f9eb5438d17e6ef[m
Merge: 5a4bb29f 7cb3ae77
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 22:06:17 2024 +0100

    Merge branch '8.19-warnings-deprecations'

[33mcommit 7cb3ae77cb5657bdd266923119c0893a3366cb61[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 21:59:40 2024 +0100

    Fix warnings and deprecations

[33mcommit 5fdd3af9969a4c9966640fda76c7fad583571ae4[m
Merge: 29e95de7 6d8ea79d
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 17:38:52 2024 +0100

    Merge pull request #1047 from MetaCoq/8.18-warnings-deprecations
    
    8.18 warnings and deprecations fixes

[33mcommit baa317c2714f7a3fc1ca38a96c368ed70aaab3f5[m
Merge: 3f5c81df 6d8ea79d
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 17:26:07 2024 +0100

    Fix warnings and deprecations in 8.19

[33mcommit 6d8ea79d6a7f299481a6f60dc128ec53a0bd1ada[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 15:27:21 2024 +0100

    Fix 8.18 warnings and deprecations

[33mcommit e0e204fb9f33b568e4828bb8b42fe0d514109902[m
Merge: 29e95de7 3ca2a6f0
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jan 26 15:03:16 2024 +0100

    Merge branch 'coq-8.17' into coq-8.18

[33mcommit 3ca2a6f07f9f05f9bcb373debd8faa39634b7ec8[m
Merge: 94999610 807fc508
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Fri Jan 26 11:21:00 2024 +0100

    Merge pull request #1046 from MetaCoq/generalize-lemmas-for-coq-malfunction
    
    Generalize lemmas for coq malfunction

[33mcommit 807fc508553158b8ed831fa748f57d0c63b391c7[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Fri Jan 26 10:42:43 2024 +0100

    verified_erasure_pipeline_lookup_env_in for all decls

[33mcommit 66e14a0506d88492925b218de937bdab60a148de[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Fri Jan 26 10:41:59 2024 +0100

    strengthen principal_type_ind

[33mcommit 949996105446e9de6c2d5493f32cdb62d4d54f12[m
Merge: 1468636c 9332f054
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Jan 25 18:26:56 2024 +0100

    Merge pull request #1045 from MetaCoq/coq-8.17-warnings
    
    Fix remaining warnings, minor fixups

[33mcommit 9332f054d1a0d930e445d3a0973b2dfebf3d116d[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Jan 25 16:17:25 2024 +0100

    Fix remaining warnings, minor fixups

[33mcommit 5a4bb29ffe094d8b2db0d24623a2bdf5560d8545[m
Merge: a4caaaec 8d4a322e
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Jan 25 09:37:47 2024 +0000

    Merge pull request #1044 from MetaCoq/update-main
    
    Update main

[33mcommit b3f2a125c369cf6dfc578cb3d8ad9428ced6a969[m
Author: Yishuai Li <liyishuai.lys@alibaba-inc.com>
Date:   Thu Jan 25 16:53:15 2024 +0800

    CI: fix concurrency and trim versions

[33mcommit 1468636c26a7a5563dca421160fa04cf392e2260[m
Merge: ec3d756d 553263db
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 23:22:16 2024 +0000

    Merge pull request #1043 from MetaCoq/mclist-fix
    
    Strengthen In_size lemma

[33mcommit 8d4a322e81afb3eaa6a8811c8b002803969dd08c[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 16:01:13 2024 +0100

    Update build.yml

[33mcommit ec3d756d5b05d11bbb11c4a1c202be3bbf1dfb01[m
Author: Jason Gross <jgross@mit.edu>
Date:   Wed Jan 24 09:05:23 2024 -0800

    Restore compatibility with OCaml < 4.13 (#1023)
    
    Fixes #1022 after #998

[33mcommit 553263db8b5b4bb022a95bfb2cfd56386c58c861[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 11:27:24 2024 +0100

    Strenghten In_size lemma

[33mcommit a4caaaece9e0e991a8395b4a47061c826fa12ff3[m
Merge: 9b70a137 cbd4b054
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 09:14:52 2024 +0000

    Merge pull request #1041 from SkySkimmer/uneven
    
    Remove unused Require Even (Even has been removed from stdlib in 8.19)

[33mcommit 3f5c81dfc87e0d8a995c4c9d56d8e580a30ff4e9[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 09:39:35 2024 +0100

    Fixes in Makefiles and test-suite

[33mcommit 0a23e4ebdc0e550ea6db355f426e4f55f441e58c[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 08:23:25 2024 +0100

    Fix opam deps

[33mcommit cd8d39ea9097503726d61dfbcf6d68aa8a72a2e1[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Jan 24 08:00:49 2024 +0100

    Update to 8.19

[33mcommit 698f904968094385b0b4328f8f9c72a817879062[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jan 23 18:00:16 2024 +0100

    Fix template after update

[33mcommit 675d79d55e487a1739c43c9fc5922e3d04bc5e77[m
Merge: 9b70a137 29e95de7
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jan 23 17:31:53 2024 +0100

    Merge branch 'coq-8.18' into coq-8.19

[33mcommit 29e95de74c6466052e0884f0321090bc0b6b7935[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jan 23 16:44:25 2024 +0100

    Fix test-suite due to changes in 8.18

[33mcommit a6214f9b606835b8ab1b9b700e4d24fbf21dc903[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jan 23 16:04:01 2024 +0100

    Fixes after merge

[33mcommit 8c7a672a39ba0c062c2a8c7bfebe397d78525710[m
Merge: 56743e22 4dc7c478
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Jan 23 16:03:44 2024 +0100

    Merge branch 'coq-8.17' into coq-8.18

[33mcommit cbd4b054f7bae7188f9aad2b77708042ed6c3234[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Jan 18 15:51:01 2024 +0100

    Remove unused Require Even (Even has been removed from stdlib in 8.19)

[33mcommit ad8d2afd783718d48102f64305a9f7bdee62e69c[m
Author: Yishuai Li <liyishuai.lys@alibaba-inc.com>
Date:   Wed Jan 17 22:07:40 2024 +0000

    CI: multiple OCaml versions

[33mcommit 4dc7c478e410fdb6bdf7f21a881ce37ad6fe161f[m
Author: Jason Gross <jgross@mit.edu>
Date:   Sat Jan 13 10:40:50 2024 +0000

    Add some debugging suggestions for quotation (#1031)

[33mcommit c36b24b90bd35261ab4d1b027e548197c2ced98c[m
Merge: e9b17dcf f526608c
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Dec 22 14:34:02 2023 +0100

    Merge pull request #1033 from MetaCoq/primitive-flags
    
    Primitive flags

[33mcommit f526608c6a3b6d126dfc6443c05de9520aa0256d[m[33m ([m[1;31mupstream/primitive-flags[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Dec 21 18:05:27 2023 +0100

    Add an EPrimitiveFlags to control the presence of ints/floats/arrays

[33mcommit c1414bf605e30556edeb7a24a94a0e9f5510f924[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Dec 21 11:39:02 2023 +0100

    Make EPrimitive universe polymorphic so it can apply to term types in Set or Type

[33mcommit e9b17dcf748fef32222139499b92a48079386cd4[m
Merge: b646cd34 078344ed
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Dec 19 16:29:46 2023 +0100

    Merge pull request #1007 from yannl35133/rejudgment
    
    More unified judgment type and All_local_env

[33mcommit 078344edd231b82b7d7e8c225fd6908fbd0ac860[m
Author: Yann Leray <yannl35133@gmail.com>
Date:   Sat Dec 16 20:17:34 2023 +0100

    Fix translations

[33mcommit 3a488f5b987462c916edc3cb8abe2853d7a2822f[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Fri Dec 15 16:51:18 2023 +0100

    Rename LevelAlg -> Universe.t -> Sort.t, equality takes conv_pb

[33mcommit e4a179c9a09d8aba5314e1d79815b92ab5837766[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Wed Nov 15 19:45:10 2023 +0100

    Change typing rules for lambda prod and letin

[33mcommit 9b74e81f7a845f10dae658c10af1b5cab61436b7[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Wed Nov 8 17:44:41 2023 +0100

    Shared app_context, integrated Σ in ctx_inst

[33mcommit c9f169bd1cf05279c8ad65d8687e3b15a8fef94f[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Tue Nov 7 16:36:03 2023 +0100

    More unified All_local_env, cleaned up {PCUIC,}Typing

[33mcommit 8a07c409e66430f8f2abc902475b72a27d63819e[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Fri Oct 27 11:29:58 2023 +0200

    More unified "judgment" type

[33mcommit b646cd34fdf6764add5b6f2490d0d3098b16194b[m
Merge: 943772db f1a445bc
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Dec 13 13:53:26 2023 +0100

    Merge pull request #1030 from MetaCoq/typed-extraction-integration
    
    Typed extraction integration

[33mcommit f1a445bc3a1e557ee65cbe3d34e433152c39537f[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Dec 13 11:17:20 2023 +0100

    Finish the proof of preservation of eta-expansion by dearging

[33mcommit ea4ab2dd43e2bd2f985dcd200e04a76b0ba541d4[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Dec 12 17:47:46 2023 +0100

    Prove that dearging preserves eta-expanded constructors and fixpoints (tricky!)

[33mcommit dd294c9d65bd9674b2e146468e52329f8bddf7d4[m
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Sun Dec 10 15:29:58 2023 +0100

    Adapt to Coq PR#18397: Declare.declare_variable now takes a "variable_declaration".

[33mcommit 9b70a137ed8e0b00c7a3b76a44cac9ff738e8ab4[m
Merge: 194116d4 b4575af9
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Sat Dec 9 11:36:38 2023 +0100

    Merge pull request #1028 from proux01/fix_coq_18374
    
    Fix breakage from https://github.com/coq/coq/pull/18374

[33mcommit b4575af931986221c30b9c4aba0e6a8be581f277[m
Author: Pierre Roux <pierre.roux@onera.fr>
Date:   Fri Dec 8 17:26:29 2023 +0100

    Fix breakage from https://github.com/coq/coq/pull/18374

[33mcommit c2620bb8002a988de5c3d281e9067f0079be9380[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Dec 7 14:11:47 2023 +0100

    Typed erasure variant

[33mcommit f7918c380cc4d866d026379ca69675483c9d8d71[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Dec 5 12:03:51 2023 +0100

    Generalized theorems for typed optimization

[33mcommit 40d2284fc809addac642a2b381de4c9680686e04[m[33m ([m[1;31mupstream/typed-extraction-correctness[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 28 15:53:40 2023 +0100

    Finished proof of correctness for typed erasure

[33mcommit e60bf4d3b885a4007cb618891a6149d1b28c3e69[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 28 14:29:38 2023 +0100

    WIP on wellformedness proof

[33mcommit 5e9ae4f4f92fda8c3af2017c1e52f017ca37eb23[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Nov 27 18:11:53 2023 +0100

    Adapted extraction correctness, only remaining wf_glob proofs

[33mcommit 943772db4bb0067b26ee011eb2a712c35d858e74[m
Merge: aec0e80e 4d6d0147
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Dec 4 16:44:40 2023 +0100

    Merge pull request #1027 from MetaCoq/primitive-arrays-eval
    
    Primitive evaluation

[33mcommit 4d6d0147fcec9600ac3241afe44cab851fd43dfb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Dec 4 15:02:08 2023 +0100

    Adapt WcbvEvalNamed to primitives (new values)

[33mcommit 69a80fcee1b93fcf17c212f05a9c8402df687846[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Dec 1 18:12:07 2023 +0100

    Adapted erasure to new array evaluation rules, except named wcbveval relation

[33mcommit 822cb61d5fe95d68bf13fbf2b0ebd0b55e2396a6[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 18:21:53 2023 +0100

    Adapt evaluation to primitive arrays (including PCUIC)

[33mcommit 022608fcd1d60e40bd39c8a846dc1c78129481c8[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 14:49:25 2023 +0100

    Evaluation for arrays

[33mcommit aec0e80e92d93aed6276b023704a786f50eb86e3[m
Merge: d6acef96 ecf08b79
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Dec 4 15:12:12 2023 +0100

    Merge pull request #1006 from yannl35133/LSP-support
    
    LSP Support

[33mcommit ecf08b79fcbfa6f0aede14db548bb57dce99a4e5[m
Merge: 921a531d d6acef96
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Dec 4 15:11:37 2023 +0100

    Merge branch 'coq-8.17' into LSP-support

[33mcommit d6acef96dcaa70397023970ebf34e98a8773c14d[m
Merge: 27148be6 3a51898a
Author: Jason Gross <jgross@mit.edu>
Date:   Sun Dec 3 16:13:36 2023 -0800

    Merge pull request #1024 from JasonGross/coq-8.17+restore-quotation
    
    Fix quotation after primitive array support

[33mcommit 3a51898a87f196da69049b82af2e61f80b68c628[m
Author: Jason Gross <jgross@mit.edu>
Date:   Sun Dec 3 09:20:56 2023 -0800

    Revert "Disable quotation module build"
    
    This reverts commit 8b4d7a9d451f7158073a7c4d6d6b7dfe23cabb96.

[33mcommit 3f0d369baf0dde792ca58aba4315bffabede6360[m
Author: Jason Gross <jgross@mit.edu>
Date:   Thu Nov 30 21:24:18 2023 -0800

    Revert "Disable quotation opam module dependency"
    
    This reverts commit 1dd89940da55a7398ef1114d79396acbdcaac47d.

[33mcommit ffc04ea97e1c445edad78f0c748e8f2f7d493d02[m
Author: Jason Gross <jgross@mit.edu>
Date:   Thu Nov 30 21:24:04 2023 -0800

    Revert "Disable the opam quotation package for now"
    
    This reverts commit 7dd6de84f34317547573b7a90c95f58208f20706.

[33mcommit dd498eade18f40cbcc361e975e3129f7bdecdd66[m
Author: Jason Gross <jgross@mit.edu>
Date:   Thu Nov 30 18:37:42 2023 -0800

    Fix quotation after primitive array support

[33mcommit 27148be6729ab74ceea41f267370b4b238a01258[m
Merge: 41123c4f 6c0bcf5d
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Fri Dec 1 15:33:21 2023 +0100

    Merge pull request #1025 from MetaCoq/squash-typing-precond
    
    squash typing hypothesis in precond

[33mcommit 6c0bcf5d6ee22234a240d8c40c8c61ca095aacff[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Fri Dec 1 14:59:47 2023 +0100

    squash typing hypothesis in precond

[33mcommit 41123c4f4609dda6a5159c5ae2842f3b1c592132[m
Merge: fb6a4d75 7dd6de84
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 18:22:18 2023 +0100

    Merge pull request #998 from MetaCoq/primitive-arrays
    
    Support primitive array terms

[33mcommit 7dd6de84f34317547573b7a90c95f58208f20706[m[33m ([m[1;31mupstream/primitive-arrays[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 14:51:05 2023 +0100

    Disable the opam quotation package for now

[33mcommit 1dd89940da55a7398ef1114d79396acbdcaac47d[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 14:04:52 2023 +0100

    Disable quotation opam module dependency

[33mcommit 8b5049ff2b3727575eea47bafb981c897c25e58a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 30 12:07:40 2023 +0100

    Fix translations, and a bit of quotation, up-to an issue with nested
    inductive definitions.

[33mcommit 194116d4f80dc53253f8730aa822c52225731d71[m
Merge: 72618e50 8d6c1cc3
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Wed Nov 29 19:44:50 2023 +0100

    Merge pull request #1015 from SkySkimmer/sort-poly-ind
    
    Adapt to coq/coq#18331 (mind_kelim -> mind_squashed)

[33mcommit 56743e220ea62bd622ce010309ed5a0cb302e98a[m
Author: Jason Gross <jgross@mit.edu>
Date:   Tue Nov 28 11:31:13 2023 -0800

    Update dependabot.yml to update coq-8.18

[33mcommit fb6a4d754ac7542bcabd0328f57d8df7c5e1f8b4[m
Author: Jason Gross <jgross@mit.edu>
Date:   Tue Nov 28 11:30:29 2023 -0800

    Update dependabot.yml to update coq-8.18

[33mcommit 133b5ad7ff8f9bff4c54e68444b88ae640faadb5[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Nov 24 16:55:49 2023 +0100

    Fixes after rebase

[33mcommit 8b4d7a9d451f7158073a7c4d6d6b7dfe23cabb96[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Nov 24 16:55:42 2023 +0100

    Disable quotation module build

[33mcommit 335484751ad42f42246fcef24565ee4058e92bdb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Nov 24 16:36:10 2023 +0100

    Adapt erasure for primitive arrays

[33mcommit 8ecbd0e3764556dbe0e9ae32d54619a2d74cc079[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 23 15:21:49 2023 +0100

    WIP in erasure of arrays

[33mcommit 69c1f0583615141690186478da6d1dd04e3301af[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Nov 24 16:34:36 2023 +0100

    In erasure, must update solve_all to automate proofs

[33mcommit 51cb57dd479aa8dd5c627c9e79b043765cba6532[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 21 17:00:33 2023 +0100

    Typechecking of arrays

[33mcommit 67bba980bd387059ce16998c01824f8002750872[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 21 15:25:11 2023 +0100

    Updatet SafeConversion to arrays

[33mcommit 3ee01a38d7f3dddc5d8c58a1304fe8dc5523b827[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Nov 20 15:34:12 2023 +0100

    Update PCUICPosition to include arrays

[33mcommit e93c39cae5a7f8d0267286d97ade963f9f2d6dc3[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Nov 17 17:49:00 2023 +0100

    Done with template <-> PCUIC. Working on safe checker

[33mcommit a7af7452e0d26efe5ccfd3b9252ea54d5228fa5e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 7 14:04:45 2023 +0100

    Adapted all of PCUIC to primitive arrays (and in general term containers in primitives)

[33mcommit 26779c7ca53e5c69c807fa86ee3353728bd87355[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 7 13:37:24 2023 +0100

    Proved subject reduction for arrays

[33mcommit c86a3a8fa8c743be1e5a62193b45d7f898c68286[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Nov 6 17:45:08 2023 +0100

    Alpha-conv and validity done

[33mcommit ed544ea33a9010c9f5a0ed36f2de733dd08d287d[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Nov 6 14:32:00 2023 +0100

    WIP up to confluence for arrays

[33mcommit 45666652abfbc44e3e23289ddfa4d107a2b302af[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Oct 30 12:51:51 2023 +0100

    Support primitive array terms

[33mcommit 72618e50add6427f14471ba4d64f03cc17e4cea9[m
Merge: 285a97ac 73b1a26d
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Tue Nov 21 16:58:00 2023 +0100

    Merge pull request #1011 from Villetaneuse/rm_arith_files
    
    Adapt wrt Coq/Coq#18164

[33mcommit 73b1a26d774421509053b712355c8a29304c1de3[m
Author: Pierre Rousselin <rousselin@math.univ-paris13.fr>
Date:   Sat Nov 11 10:57:31 2023 +0100

    Adapt wrt Coq/Coq#18164

[33mcommit 8d6c1cc32ccdfc0aeaa40978a81464467cc59712[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Mon Nov 20 15:36:11 2023 +0100

    Adapt to coq/coq#18331 (mind_kelim -> mind_squashed)

[33mcommit 6eef155ea2a53e81199c8962402bc2b114c1e4ab[m
Merge: b63f41ad f9414954
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Wed Nov 15 16:36:50 2023 +0100

    Merge pull request #1014 from MetaCoq/transform-extends-split
    
    Transform extends split

[33mcommit f94149545119a92e9a11b08c5e90df97fd7b8117[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Wed Nov 15 15:20:55 2023 +0100

    fix after rebase

[33mcommit 3a954d5f98753e17bb3f0ed544ec131ec759870f[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Nov 14 21:02:59 2023 +0100

    prove missing lemmas of the pipeline

[33mcommit b4ef021620bb25dffd3f137f71cadecc9980c960[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Nov 14 21:02:44 2023 +0100

    separate extends and extends_eprogram

[33mcommit b63f41ad2c7a4e6f0ec2ccbc5613712fc00b8fa4[m
Merge: b33a9bd9 27d6ad2e
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Nov 15 13:50:53 2023 +0100

    Merge pull request #1013 from MetaCoq/compile-pipeline-app
    
    Compile pipeline app: applications of eta-expanded terms are preserved by the erasure pipeline.
    This introduces a judgment for normal forms (and neutrals), and a proof that the PCUICExpandLets transformation preserves normal forms. Also introduces a more positive `nisErasable` notion that characterizes non-erasable/relevant terms.

[33mcommit 27d6ad2e0641426ffcaeec18be1c81144a38da37[m[33m ([m[1;31mupstream/compile-pipeline-app[m[33m)[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Nov 15 13:48:09 2023 +0100

    Fix unqualified, ambiguous imports

[33mcommit 64b8171938185397563976198e53c03529246376[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Nov 15 11:59:44 2023 +0100

    Cleanup ErasureCorrectness

[33mcommit 84a264f46ccac76cb2d724ebc4cb7258528fb5dd[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Nov 14 15:42:55 2023 +0100

    Preservation of applications for proven for the whole pipeline

[33mcommit 537e2489bdbf6ca84a40a2ede6900ab0b2ca9fac[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 9 18:15:14 2023 +0100

    Use normal form characterization in nisErasable

[33mcommit 1f4249d6879e8d17975d82bf907b062ee244f0bd[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Nov 9 18:13:12 2023 +0100

    Definition of normal forms and proof that they reduce only to themselves

[33mcommit 0def70319e67b88c432797b3fe799fc0ad0c41a8[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Oct 26 12:59:40 2023 +0200

    WIP on normal predicate

[33mcommit 9ed43d79ec39f68d984721236c5d8e70dbfb5816[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Oct 23 14:30:32 2023 +0200

    Prove app preservation for erase and let expansion

[33mcommit a6b7428d1abb1c344f3dc0b913e216033bbe6428[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Oct 20 11:13:14 2023 +0200

    Show that applications of eta-expanded functions are preserved

[33mcommit 285a97ac67ec51be48547de7e936d94a7634cabf[m
Merge: 4b0d5da4 0571a045
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Mon Nov 13 15:53:51 2023 +0100

    Merge pull request #1009 from SkySkimmer/ci-relevance
    
    Adapt to coq/coq#18280 (case relevance outside case info)

[33mcommit 4b0d5da4aac1d454506387d9a69e0648fa024134[m
Merge: 472ac7b1 d6ada949
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Mon Nov 13 14:39:08 2023 +0100

    Merge pull request #1010 from ppedrot/glob-evar-kinds
    
    Adapt w.r.t. coq/coq#18294.

[33mcommit d6ada9495fb99fd6b5f1ed319e32b9ccebc56dd3[m
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Fri Nov 10 17:12:17 2023 +0100

    Adapt w.r.t. coq/coq#18294.

[33mcommit 0571a04570891960df52546ba064d86624090f5c[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Nov 9 16:37:48 2023 +0100

    Adapt to coq/coq#18280 (case relevance outside case info)

[33mcommit 478ab43c9fe4ad87af59499e23a8051ad3561035[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Nov 9 16:33:12 2023 +0100

    Fix .merlin targets

[33mcommit 921a531d36269dae44f32ca4c481e01a007d08fc[m
Author: Yann Leray <yann.leray@inria.fr>
Date:   Tue Nov 7 18:47:21 2023 +0100

    LSP Support

[33mcommit 472ac7b1f7e4aa91d79e39da1ccccec14170dac0[m
Merge: f593f016 84c46e5d
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Mon Nov 6 21:44:50 2023 +0100

    Merge pull request #984 from SkySkimmer/sort-poly
    
    Adapt to coq/coq#17836 (sort poly)

[33mcommit f593f01650bde0d33da3a61dec76552d77c397c1[m
Merge: 64ce7859 67cd5e95
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Sat Nov 4 20:17:24 2023 +0100

    Merge pull request #1005 from SkySkimmer/let-abstract
    
    Adapt to coq/coq#17576 (declare_variable takes typing flags argument)

[33mcommit 67cd5e957686a4db0d1419139926aa53e95d511f[m
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Thu Nov 2 15:28:54 2023 +0100

    Adapt to coq/coq#17576 (declare_variable takes typing flags argument)

[33mcommit 40252562493c6ebf62f023f8ba0af7c29aa07a50[m[33m ([m[1;33mtag: [m[1;33mv1.2.1-8.18[m[33m)[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 14:35:50 2023 +0100

    remove nix on 8.18

[33mcommit e577333072ab594ea43c2ff38cb389d86c32624b[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 14:29:57 2023 +0100

    fix Makefile and opam files

[33mcommit b33a9bd92a271484efeca0c5e6c66c61196eee99[m[33m ([m[1;33mtag: [m[1;33mv1.2.1-8.17[m[33m)[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 14:29:57 2023 +0100

    fix Makefile and opam files

[33mcommit e649edb1e9a25dc0e9147493b1c99f3ebe938943[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 13:00:40 2023 +0100

    disable quick target in CI - it is not quicker

[33mcommit 6d98589a26b8c61569328633e78f4977c9c11eae[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 12:59:27 2023 +0100

    eliminate race condition for opam compilation

[33mcommit 7d0a7a6760ee62845855697756ef4213dbda8a7e[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 12:59:27 2023 +0100

    eliminate race condition for opam compilation

[33mcommit 045ec007cad116d80c099081a5cb6426e07fbc59[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Nov 1 11:31:49 2023 +0100

    disable quick target in CI - it is not quicker

[33mcommit 1f24609ae9f4e8657df036092ad80da657cac125[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 17:44:34 2023 +0200

    move implement_box_transformation to coq-malfunction

[33mcommit 6d8b2f556ff98bb3a98f24e0597a2427e4d4f076[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 13:20:58 2023 +0200

    add install-plugins target in Makefile

[33mcommit 2ea865ab9a1bebdee77a82c9b928b8fcb6b900c3[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 12:05:51 2023 +0200

    linearize case

[33mcommit 98b847cf74178bf8dc5bf06106799f7d957d8a96[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Thu Oct 26 17:13:18 2023 +0200

    use names in EAst.t

[33mcommit f8aba7c9b6e0e09c768a18e158a832be0a13910d[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 17:44:34 2023 +0200

    move implement_box_transformation to coq-malfunction

[33mcommit 7d58a861d92ce81e88d6cb6eeea7b7f43bec5287[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 13:20:58 2023 +0200

    add install-plugins target in Makefile

[33mcommit f7d27f7b127b447cbc9d5530a07a52df561f18cc[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Oct 25 12:05:51 2023 +0200

    linearize case

[33mcommit 79f745413bdd923ec56be86c971048e35bbe9462[m
Merge: 1e3d82d0 18a24e5a
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Thu Oct 26 19:12:46 2023 +0200

    Merge pull request #997 from MetaCoq/use-names-in-EAst
    
    use names in EAst.t

[33mcommit 18a24e5a46a60cc122a49cf48998d481661746b6[m[33m ([m[1;31mupstream/use-names-in-EAst[m[33m)[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Thu Oct 26 17:13:18 2023 +0200

    use names in EAst.t

[33mcommit 83aa0b0610db7999dc3baabc89dba4d6bf00e71a[m
Author: Jason Gross <jgross@mit.edu>
Date:   Thu Oct 19 12:04:55 2023 -0700

    Add quotation API for context and global_env_ext (#996)
    
    Useful for externally defining cojoin a la
    https://docs.google.com/presentation/d/1fUYQ_H0NAaQzCWYidUyWqKUhyHrL_5ofjzi9mzrsEEo/edit?usp=sharing

[33mcommit 64ce7859dc05816dbd383b580f3c9952faf230ed[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Tue Oct 17 17:49:53 2023 +0200

    Replace elimtype False by exfalso (#995)

[33mcommit adc980ccf69be29be24db632de9ac8321ad54d44[m
Merge: 573587b9 97911f23
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 17:11:42 2023 +0200

    Merge pull request #993 from MetaCoq/main-updates-8.18

[33mcommit 1e3d82d0e642e9e218b9c2a22b06116193e521c4[m
Merge: 65e8a936 34c831e7
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 17:11:22 2023 +0200

    Merge pull request #992 from MetaCoq/coq-8.17-updates-8.16

[33mcommit dc8a7a0f3fa28cfe58f3d806789f43903e9384be[m
Merge: 1fcd7ffb 39e31f6e
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 17:10:34 2023 +0200

    Merge pull request #991 from MetaCoq/coq-8.18-updates-8.17

[33mcommit 39e31f6e0b56cd5ad5ea557aaa65a5a801a2c241[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 17:10:12 2023 +0200

    Remove nix

[33mcommit 97911f233561cd7ad60f2d3f28af8a3c00ccf20b[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 17:09:39 2023 +0200

    Remove nix

[33mcommit 87f8ebf1a77d2fe77f5835908ebf3d736e6f6f96[m
Merge: 1fcd7ffb 34c831e7
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 15:36:04 2023 +0200

    Merge branch 'coq-8.17-updates-8.16' into coq-8.18

[33mcommit 34c831e73af5661e5b3ae2bd6c24cd056fd66eba[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 11:01:24 2023 +0200

    fix Makefile

[33mcommit 241dd7fadb4632a56a72ab5f5ae0facf382993c6[m
Merge: 65e8a936 9f7cc51e
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 16 10:23:49 2023 +0200

    Merge remote-tracking branch 'origin/coq-8.16' into coq-8.17

[33mcommit 65e8a936996c410ad5298cd7bb55a05db9686768[m
Merge: 3733e670 1dc79610
Author: nicolas tabareau <nicolas.tabareau@inria.fr>
Date:   Tue Oct 10 15:02:56 2023 +0200

    Merge pull request #990 from MetaCoq/not_isErasable
    
    add not_isErasable lemma in EArities

[33mcommit 1dc79610c4994d1b0f03150bee2d6ea65617d321[m
Author: nicolas tabareau <nicolas.tabareau@gmail.com>
Date:   Tue Oct 10 13:38:07 2023 +0200

    add not_isErasable lemma in EArities

[33mcommit 1fcd7ffbc7ec19f2849aa92cc9874edee7d38828[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Thu Oct 5 10:38:01 2023 +0200

    coq-equations.1.3+8.18

[33mcommit 3733e670de74c98c0a46620873777dee960f8de1[m
Merge: a152eecf 357e8a7d
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Oct 3 12:59:10 2023 +0200

    Merge pull request #987 from MetaCoq/verified_erasure_pipeline
    
    Verified erasure pipeline

[33mcommit 357e8a7ddd140f4396c18eb9bd95e822f9363d25[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Oct 3 11:27:01 2023 +0200

    Fix test suite

[33mcommit f2b1cc0783dd745d9dd52e562bac30221599dd63[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Oct 3 10:30:52 2023 +0200

    Fix after rebase

[33mcommit efe2b96dd74cdbcc09c652dd8eaae41e6814cbcb[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Mon Oct 2 15:21:59 2023 +0200

    fix CI

[33mcommit dfb03d1f3dd68613fc123c50683e25027b078594[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Oct 2 13:34:43 2023 +0200

    Minor fixes

[33mcommit 487cdf52b8d8edbc76a5fa3133bb141fae0dbedc[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Sep 15 14:12:38 2023 +0200

    Cleanup

[33mcommit a0dc628f1b4566c2b36dda823ee4f73ab164dff5[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Sep 13 11:31:59 2023 +0200

    Fix erasure plugin compilation

[33mcommit 708302f5901363a86bc522ba9bbeed91a1aa9366[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Sep 13 11:29:35 2023 +0200

    Cleanup a bit, remain only normalization side-conditions

[33mcommit b072acf2ec507b1fb3cbce17607d7b973e92afe1[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Sep 13 10:15:21 2023 +0200

    Filled all proofs in ErasureCorrectness

[33mcommit 681a3827e5371dacb705aa594ee1145d39e71fc9[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Sep 12 17:29:43 2023 +0200

    Refactor a bit, work on side conditions for let expansion

[33mcommit 2f5fed3109aaa1f7d8d76328cf2fb2f1084cce2d[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Sep 12 12:52:42 2023 +0200

    Finished preservation of expansion proof

[33mcommit f1699162d543998dfafd35a4562b66c2af50db97[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Sep 11 18:08:45 2023 +0200

    Prove preservation of expansion by reduction using a custom reduction relation

[33mcommit 915ce93fb1641e227e1318fba70f33e20bbb41ed[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Sep 8 17:29:53 2023 +0200

    We're missing preservation of eta-expandedness by reduction in PCUIC...

[33mcommit 0e5938a5d1b93ba7b6e1cc3344efd8673dd04c13[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Sep 7 16:33:11 2023 +0200

    Finish main erasure correctness proof. Need to move expand_lets reasoning to a first step

[33mcommit 1f1248dd3aefd63a926112949d05685b65de4938[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Sep 1 18:15:51 2023 +0200

    Proved most of the fo preservation of the lambdabox pipeline

[33mcommit 0934fc0d92d6e04933fec71f41934ebd92e4ca27[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Aug 31 18:07:10 2023 +0200

    Modify Transform class to allow showing preservation of fo values compositionally

[33mcommit 80055db424031c287f6cbf1cbc6efd3dd29e7a0a[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Aug 31 12:08:47 2023 +0200

    Finished proof of firstorder correctness for erase_pcuic_program

[33mcommit 93395bfb481db230d41b4aca9239f09e081c7718[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Wed Aug 30 11:15:21 2023 +0200

    Finish the proofs in ErasureFunction

[33mcommit 71819e7bc59d814386abdf74958f56b735da29ce[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Tue Aug 29 18:17:51 2023 +0200

    Main argument of the erasure with dependencies proof

[33mcommit 3856b002c63bf90263b70f3d53d0ffdc470cc281[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Aug 28 18:02:39 2023 +0200

    Progress on pipeline theorem proof, main argument remains

[33mcommit 7158506c5564b3f57b6240c385136a94a3ede002[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Aug 28 10:47:26 2023 +0200

    Strenghtened program extension preservation

[33mcommit 8710ece55c005349ab135dccec7c99ce306cf11f[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Aug 28 10:02:22 2023 +0200

    No need for ext proof for erasure

[33mcommit 805bbdad44325d51864e4df611efdcebce859616[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Thu Aug 24 01:42:55 2023 +0200

    Prove a more precise result about erase_global_decls with dependencies

[33mcommit e09e64d8000785ece4336394a66bb4c501e1cbbb[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Aug 21 14:44:09 2023 +0200

    Allow modifying inductive decls in generic weakenability translation proofs.
    Now parameter stripping is a weakenable translation.

[33mcommit 6a1428acb3f8073dc9f84a3b3f42e6fe8d6f8d1e[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Mon Jul 17 09:58:23 2023 +0200

    WIP stronger global weakening theorems for optimizations

[33mcommit f1a254857c202fba06cd74d12b365e591321c2c2[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Wed Jul 12 16:08:14 2023 +0200

    wellformed_annotate_env

[33mcommit 06ca492ccf37fad84a62778f1517c0683515c5ee[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Tue Jul 11 16:45:41 2023 +0200

    prove wellformedness of annotate

[33mcommit a35996168cf4dd16b13da4e1dcf9f4803cfb9f87[m
Author: Matthieu Sozeau <matthieu.sozeau@inria.fr>
Date:   Fri Jul 7 18:28:57 2023 +0200

    Fix definition of Transform.t's observational equivalence preservation

[33mcommit 7565dd43f65a0bd0268c2404b6dc929ed8bc28ab[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Thu Jul 6 15:38:40 2023 +0200

    remove assumption

[33mcommit 5bc51f5cb9f708ea3a6c8b6fcc1abe8120beed9a[m
Author: Yannick Forster <yannick.forster@inria.fr>
Date:   Thu Jul 6 15:14:02 2023 +0200

    adapt name pass to not consider box
